const CHAT="@cf/google/gemma-4-26b-a4b-it",FLUX="@cf/black-forest-labs/flux-1-schnell",T=()=>Math.floor(Date.now()/1000),N=s=>String(s||"").trim().toLowerCase(),J=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}});function hex(n=16){let a=new Uint8Array(n);crypto.getRandomValues(a);return[...a].map(x=>x.toString(16).padStart(2,"0")).join("")}function b64(a){let s="";for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s)}function ub64(s){let b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}async function hash(p,s){let k=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]),x=await crypto.subtle.deriveBits({name:"PBKDF2",salt:ub64(btoa(s)),iterations:100000,hash:"SHA-256"},k,256);return b64(new Uint8Array(x))}function txt(r){return r?.response||r?.choices?.[0]?.message?.content||r?.choices?.[0]?.text||""}async function getUser(req,e){let c=req.headers.get("Cookie")||"",m=c.match(/(?:^|;\s*)myai_session=([^;]+)/);if(!m)return null;let x=await e.DB.prepare("SELECT u.id,u.email,u.plan,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=?").bind(decodeURIComponent(m[1])).first();if(!x||x.expires_at<T())return null;return{...x,isAdmin:N(x.email)===N(e.ADMIN_EMAIL)}}async function require(req,e){let u=await getUser(req,e);if(!u)throw Error("AUTH");return u}async function vision(req){let f=await req.formData(),file=f.get("image");if(!(file instanceof File))return null;let a=new Uint8Array(await file.arrayBuffer());return{image:`data:${file.type||"image/jpeg"};base64,${b64(a)}`,prompt:String(f.get("prompt")||"").trim()}}
export default{async fetch(req,e){let u=new URL(req.url);try{
if(u.pathname==="/api/auth/register"&&req.method==="POST"){let b=await req.json(),email=N(b.email),p=String(b.password||"");if(!email.includes("@"))return J({error:"Ungültige E-Mail."},400);if(p.length<8)return J({error:"Passwort muss mindestens 8 Zeichen haben."},400);if(await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return J({error:"Konto existiert bereits."},409);let s=hex(16),t=T(),adm=N(e.ADMIN_EMAIL)===email,r=await e.DB.prepare("INSERT INTO users(email,password_hash,password_salt,plan,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(email,await hash(p,s),s,adm?"pro":"free",t,t).run(),sid=hex(32);await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(sid,r.meta.last_row_id,t+2592000,t).run();return J({user:{id:r.meta.last_row_id,email,plan:adm?"pro":"free",isAdmin:adm}},200,{"Set-Cookie":`myai_session=${encodeURIComponent(sid)}; Path=/; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax`})}
if(u.pathname==="/api/auth/login"&&req.method==="POST"){let b=await req.json(),email=N(b.email),p=String(b.password||""),x=await e.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!x||await hash(p,x.password_salt)!==x.password_hash)return J({error:"E-Mail oder Passwort ist falsch."},401);let adm=N(e.ADMIN_EMAIL)===email,t=T(),sid=hex(32);if(adm&&x.plan!=="pro")await e.DB.prepare("UPDATE users SET plan='pro',updated_at=? WHERE id=?").bind(t,x.id).run();await e.DB.prepare("INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(sid,x.id,t+2592000,t).run();return J({user:{id:x.id,email:x.email,plan:adm?"pro":x.plan,isAdmin:adm}},200,{"Set-Cookie":`myai_session=${encodeURIComponent(sid)}; Path=/; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax`})}
if(u.pathname==="/api/auth/logout"&&req.method==="POST"){let c=req.headers.get("Cookie")||"",m=c.match(/(?:^|;\s*)myai_session=([^;]+)/);if(m)await e.DB.prepare("DELETE FROM sessions WHERE id=?").bind(decodeURIComponent(m[1])).run();return J({ok:true},200,{"Set-Cookie":"myai_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax"})}
if(u.pathname==="/api/me"){let x=await getUser(req,e);return x?J({authenticated:true,user:x}):J({authenticated:false})}
if(!u.pathname.startsWith("/api/"))return e.ASSETS.fetch(req);
let me=await require(req,e);
if(u.pathname==="/api/chats"&&req.method==="GET"){let r=await e.DB.prepare("SELECT id,title,created_at,updated_at FROM chats WHERE user_id=? ORDER BY updated_at DESC").bind(me.id).all();return J({chats:r.results||[]})}
if(u.pathname==="/api/chats"&&req.method==="POST"){let t=T(),r=await e.DB.prepare("INSERT INTO chats(user_id,title,created_at,updated_at) VALUES(?,?,?,?)").bind(me.id,"Neuer Chat",t,t).run();return J({id:r.meta.last_row_id,title:"Neuer Chat"})}
let m=u.pathname.match(/^\/api\/chats\/(\d+)$/);if(m&&req.method==="GET"){let id=Number(m[1]),c=await e.DB.prepare("SELECT id,title FROM chats WHERE id=? AND user_id=?").bind(id,me.id).first();if(!c)return J({error:"Chat nicht gefunden."},404);let r=await e.DB.prepare("SELECT role,content,created_at FROM messages WHERE chat_id=? AND user_id=? ORDER BY id").bind(id,me.id).all();return J({title:c.title,messages:r.results||[]})}
if(u.pathname==="/api/chat"&&req.method==="POST"){let b=await req.json(),id=Number(b.chatId),msg=String(b.message||"").trim(),styles={sachlich:"Antworte extrem sachlich, präzise und nüchtern.",locker:"Antworte locker, freundlich und natürlich.",formell:"Antworte professionell und strukturiert.",einfuehlsam:"Antworte verständnisvoll und behutsam, aber klar.",erklaerend:"Erkläre verständlich und Schritt für Schritt.",kurz:"Antworte kurz und direkt."};if(!msg)return J({error:"Keine Nachricht."},400);if(!(await e.DB.prepare("SELECT id FROM chats WHERE id=? AND user_id=?").bind(id,me.id).first()))return J({error:"Chat nicht gefunden."},404);let cnt=await e.DB.prepare("SELECT COUNT(*) n FROM messages WHERE chat_id=?").bind(id).first(),lim=me.plan==="pro"?200:50;if(Number(cnt.n)>=lim*2)return J({error:"Nachrichtenlimit erreicht."},429);let t=T(),st=String(b.style||"sachlich");await e.DB.prepare("INSERT INTO messages(chat_id,user_id,role,content,style,created_at) VALUES(?,?,?,?,?,?)").bind(id,me.id,"user",msg,st,t).run();await e.DB.prepare("UPDATE chats SET title=CASE WHEN title='Neuer Chat' THEN ? ELSE title END,updated_at=? WHERE id=?").bind(msg.slice(0,60),t,id).run();let h=await e.DB.prepare("SELECT role,content FROM messages WHERE chat_id=? ORDER BY id DESC LIMIT 20").bind(id).all(),r=await e.AI.run(CHAT,{messages:[{role:"system",content:`Du bist MyAI. Antworte auf Deutsch, wenn Deutsch verwendet wird. ${styles[st]||styles.sachlich}`},...(h.results||[]).reverse().map(x=>({role:x.role,content:x.content}))],chat_template_kwargs:{enable_thinking:false}}),ans=txt(r)||"Keine Antwort erhalten.";await e.DB.prepare("INSERT INTO messages(chat_id,user_id,role,content,style,created_at) VALUES(?,?,?,?,?,?)").bind(id,me.id,"assistant",ans,"assistant",T()).run();return J({response:ans})}
if(u.pathname==="/api/messages"&&req.method==="POST"){let b=await req.json(),id=Number(b.chatId);if(b.role!=="assistant")return J({error:"Ungültig."},400);if(!(await e.DB.prepare("SELECT id FROM chats WHERE id=? AND user_id=?").bind(id,me.id).first()))return J({error:"Chat nicht gefunden."},404);await e.DB.prepare("INSERT INTO messages(chat_id,user_id,role,content,style,created_at) VALUES(?,?,?,?,?,?)").bind(id,me.id,"assistant",String(b.content||"").slice(0,120000),"assistant",T()).run();return J({ok:true})}
if(u.pathname==="/api/history"){let r=await e.DB.prepare("SELECT id,title,created_at,updated_at FROM chats WHERE user_id=? ORDER BY updated_at DESC").bind(me.id).all();return J({chats:r.results||[]})}
if(u.pathname==="/api/pro/redeem"&&req.method==="POST"){let code=String((await req.json()).code||"").trim().toUpperCase(),p=await e.DB.prepare("SELECT * FROM pro_codes WHERE code=?").bind(code).first();if(!p||p.uses>=p.max_uses||(p.expires_at&&p.expires_at<T()))return J({error:"Pro-Code ist ungültig, abgelaufen oder bereits verwendet."},400);await e.DB.batch([e.DB.prepare("UPDATE pro_codes SET uses=uses+1 WHERE id=?").bind(p.id),e.DB.prepare("UPDATE users SET plan='pro',updated_at=? WHERE id=?").bind(T(),me.id)]);return J({message:"MyAI Pro wurde aktiviert."})}
if(u.pathname==="/api/image"&&req.method==="POST"){if(me.plan!=="pro")return J({error:"Bildgenerierung ist eine Pro-Funktion."},403);let b=await req.json(),p=String(b.prompt||"").trim();if(!p)return J({error:"Bitte Prompt eingeben."},400);let r=await e.AI.run(FLUX,{prompt:p,steps:4});if(!r?.image)return J({error:"FLUX hat kein Bild zurückgegeben."},500);return J({image:"data:image/jpeg;base64,"+r.image})}
if(u.pathname==="/api/vision"&&req.method==="POST"){if(me.plan!=="pro")return J({error:"Bildanalyse ist eine Pro-Funktion."},403);let b=await vision(req);if(!b)return J({error:"Kein Bild übertragen."},400);let r=await e.AI.run(CHAT,{messages:[{role:"user",content:[{type:"text",text:b.prompt||"Beschreibe und analysiere dieses Bild kurz und klar auf Deutsch."},{type:"image_url",image_url:{url:b.image}}]}]});return J({response:txt(r)||"Keine Analyse erhalten."})}
if(u.pathname==="/api/admin/users"&&req.method==="GET"){if(!me.isAdmin)return J({error:"Kein Admin-Zugriff."},403);let r=await e.DB.prepare("SELECT id,email,plan,created_at FROM users ORDER BY created_at DESC").all();return J({users:r.results||[]})}
m=u.pathname.match(/^\/api\/admin\/users\/(\d+)\/plan$/);if(m&&req.method==="POST"){if(!me.isAdmin)return J({error:"Kein Admin-Zugriff."},403);let id=Number(m[1]),p=(await req.json()).plan==="pro"?"pro":"free";if(id===me.id&&p==="free")return J({error:"Admin-Konto kann nicht auf FREE gesetzt werden."},400);await e.DB.prepare("UPDATE users SET plan=?,updated_at=? WHERE id=?").bind(p,T(),id).run();return J({ok:true})}
if(u.pathname==="/api/admin/pro-codes"&&req.method==="POST"){if(!me.isAdmin)return J({error:"Kein Admin-Zugriff."},403);let b=await req.json(),days=b.days?Number(b.days):null,code;do{code="MYAI-"+hex(4).toUpperCase()+"-"+hex(4).toUpperCase()}while(await e.DB.prepare("SELECT id FROM pro_codes WHERE code=?").bind(code).first());let exp=days?T()+days*86400:null;await e.DB.prepare("INSERT INTO pro_codes(code,expires_at,max_uses,uses,created_by,created_at) VALUES(?,?,?,?,?,?)").bind(code,exp,1,0,me.id,T()).run();return J({code,expires_at:exp})}
m=u.pathname.match(/^\/api\/admin\/users\/(\d+)\/history$/);if(m&&req.method==="GET"){if(!me.isAdmin)return J({error:"Kein Admin-Zugriff."},403);let r=await e.DB.prepare("SELECT role,content,created_at FROM messages WHERE user_id=? ORDER BY created_at,id").bind(Number(m[1])).all();return J({messages:r.results||[]})}
return e.ASSETS.fetch(req)
}catch(x){if(x.message==="AUTH")return J({error:"Bitte zuerst anmelden."},401);return J({error:"Serverfehler.",details:x.message},500)}}};
